# Generated by Django 4.2.6 on 2023-11-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tunnel_inf', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tunnel_sup', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
