# Generated by Django 4.2.6 on 2023-11-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticker', '0002_alter_ticker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
